### ISSUE TITLE
Provide status codes in service thrown error objects

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#152]

**Comment by peterpolman** [comment]
In scope: move messages into constants and improve error messaging by making errors be more declarative of the issue encountered.

**Comment by bram-rongen** [comment]
I'd like to argue we should not have status codes in service errors. Any service error should either cause a `500` or be handled by the controller if it is to be expected. Services can potentially also be used outside of controllers and so should not know about or have any responsibilities for http communication.
