### ISSUE TITLE
AWS CodeDeploy often stuck on install step. Reboot solves issue

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#157]
Problem:
Github CD manages to create a package and trigger codedeploy-agent. But the agent not always manages to run through the deployment steps. If it goes wrong the agent usually times out at the install step (unpack package). 

Solution:
A reboot if the instance and a restart of the app enables codedeploy-agent to redeploy properly. 

Ideas: Check if the package size is an issue, see what happens

**Comment by bram-rongen** [comment]
We stopped using CodeDeploy for now, will have to clean up once we switch production as well

**Comment by peterpolman** [comment]
Sounds good to me! Will you use this task for that? Otherwise it could be closed imo.

**Comment by bram-rongen** [comment]
Yeah, I was thinking of using this ticket for it :)
