### ISSUE TITLE
Automatically run migrations on deployment

### ISSUE THREAD

**Issue by bram-rongen** [thxprotocol/api#161]
Add health check to make nodes unhealthy when not all migrations have run and call migrations to be run from CI/deployment command

Difficulties here are that the migrations are run as typescript files where the production image doesn't have typescript installed. 

Some less than optimal solutions:
- [ ] Copy in the raw migrations and migration config and use `npx ts-node` which will be downloaded automatically
- [x] make migrations in js (will have to "migrate" the changelog collection so migrations aren't run again
- [x] Push a dev image to the registry, create a dev task on ECS and run from there

**Comment by peterpolman** [comment]
In develop the migrations are already in js I guess. I've changed this recently

**Comment by peterpolman** [comment]
There should only be 5 records in the changelog collection that need their file extension changed before running the js migrations. I would suggest to prep for this! Let me know if you agree

**Comment by bram-rongen** [comment]
Yes, true. It's a simple db update and should be fine!

**Comment by bram-rongen** [comment]
BTW, why do you use dotenv directly instead of importing secrets in the migrate-mongo conf?

**Comment by peterpolman** [comment]
No reason, feel free to adjust!
