### ISSUE TITLE
Introduce POST, GET token/erc20/* endpoints for Limited and Unlimited token discovery

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#243]
This scopes the backend tasks of https://github.com/thxprotocol/dashboard/issues/17

Practically we will need to:
- [x] Add TokenService with create, deploy, get, getAll operations
- [x] GET, GET all, POST `/erc20/:id` endpoints. Use the ObjectID of the Token Collection here.
- [x] Tests for token management 

- Mind that onchain data will of course not be deleted.

**Comment by GarfDev** [comment]
- Also, add token model in `auth` app to store tokens created by a user and add a proxy for it into `api` service

**Comment by peterpolman** [comment]
@GarfDev We will also need a migration to store all existing token contracts in the database.
