### ISSUE TITLE
Add controller to deposit and increase pool balance

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#280]
**Problem**
Currently when a pool is deployed for a LimitedSupplyToken the full minted supply (held by the API admin account) is deposited into the pool. This makes it hard for the user to start different pools with various amounts of the same token.

**Solution**
Provide endpoints that could be called by the Dashboard app to make a deposit from the admin account to the pool address. It should be possible to specify an amount and transferred with the use of the pools deposit method.

**Comment by valeriagrazzini** [comment]
@peterpolman is not the same behaviour of the controller "CreateDepositController"?
