### ISSUE TITLE
As a pool owner I want to add members manually

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#306]
> I guess we can just add a "+ Add member" button on the members overview page, open a modal, provide an address and call the API on submit
> the POST /v1/members is already there I think, but I'm not sure if Dashboard has the correct scopeset for it

**Comment by peterpolman** [comment]
@GarfDev Please ping me if you run into scope/authorization issues for this task!

**Comment by GarfDev** [comment]
I had transaction scope after puull latest develop, but managed to resolve it myself

**Comment by peterpolman** [comment]
Cool cool, just as an FYI these are the things to check when running into auth related scope issues:
- whitelisted scopes in clients collection in auth db
- requested scopes in OIDC scope configuration in wallet and dashboard projects
- available scopes in OIDC config in auth project

**Comment by GarfDev** [comment]
This task is done with PRs:
[API]: https://github.com/thxprotocol/api/pull/316
[Dashboard]: https://github.com/thxprotocol/dashboard/pull/55
@peterpolman
