### ISSUE TITLE
Introduce poolId referencing (instead of poolAddress)

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/api#331]

**Comment by peterpolman** [comment]
@valeriagrazzini It might be easier if I grab this task https://github.com/thxprotocol/api/issues/319 since I can combine the work easily with the work for this task.

**Comment by valeriagrazzini** [comment]
Sure, please go ahead

Il mar 21 giu 2022, 15:15 Peter Polman ***@***.***> ha
scritto:
