### ISSUE TITLE
Creating first reward in the asset pool does not respect metadata input

### ISSUE THREAD

**Issue by robertragas** [thxprotocol/api#76]
## Problem
The first reward in an asset pool will default to the following metadata 
    "title": "Complete your profile!",
    "description": "You should do this and that...",
Regardless of what you fill in.

## How to test
- [ ] Create a new asset pool
- [ ] Create a new reward and fill in a title and description of your liking
- [ ] Try to fetch the reward again and see the metadata is incorrect
- [ ] Try to create second reward and see now it will have the correct metadata

## Screenshots
Screenshot of creating the reward
![Screen Shot 2020-12-23 at 4 12 22 PM](https://user-images.githubusercontent.com/19951171/103011481-4b610000-453a-11eb-83f4-c87fc582017b.png)

Screenshot of fetching the reward
![Screen Shot 2020-12-23 at 4 12 42 PM](https://user-images.githubusercontent.com/19951171/103011519-5d42a300-453a-11eb-89fd-e6b62264b834.png)

**Comment by peterpolman** [comment]
@robertragas Can we deprecate the fields `reward.title` and `reward.description`? The API no longer requires the information and it causes issues when starting a poll for an existing reward. 

If agreed I will remove the fields from the GET operation and no longer require it for  the POST and PATCH operations. You will only need to pass the `withdrawAmount` and `withdrawDuration` to set up a reward.  I guess this will still work in you usecase.

**Comment by peterpolman** [comment]
Deprecating the field will also solve the issue here: https://github.com/thxprotocol/api/issues/11

**Comment by peterpolman** [comment]
@robertragas We have discussed this, but I can't find the outcome anywhere.. If I remember correct we decided to do without the reward metadata right?
